server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Core
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: Support
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, /inventories/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Core
          uri: http://core:8080
          predicates:
            - Path=/orders/**, 
        - id: Support
          uri: http://support:8080
          predicates:
            - Path=/deliveries/**, /inventories/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
